#!/usr/bin/env bash
# migrate.sh — Migrate bootstrap state from local → S3
#
# Usage:
#   chmod +x migrate.sh
#   ./migrate.sh
#
# Requirements:
#   - terraform >= 1.10 (for native S3 locking via use_lockfile)
#   - AWS credentials with S3 + ECR permissions
#   - jq (for parsing terraform output)
#
# Idempotent: safe to rerun. If state is already in S3, the script exits early.

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Pre-flight checks ─────────────────────────────────────────────────────────
command -v terraform &>/dev/null || error "terraform not found in PATH"
command -v jq        &>/dev/null || error "jq not found — install with: apt install jq / brew install jq"

TF_VERSION=$(terraform version -json | jq -r '.terraform_version')
REQUIRED_MINOR=10
MINOR=$(echo "$TF_VERSION" | cut -d. -f2)
if [[ "$MINOR" -lt "$REQUIRED_MINOR" ]]; then
  error "Terraform >= 1.10 required for native S3 locking (found $TF_VERSION)"
fi
info "Terraform $TF_VERSION — OK"

# ── Idempotency guard ─────────────────────────────────────────────────────────
# If backend.tf contains 'backend "s3"' NOT preceded by a comment, migration has already run.
BACKEND_FILE="backend.tf"
if grep -v '^[[:space:]]*#' "$BACKEND_FILE" | grep -q 'backend "s3"' 2>/dev/null; then
  warn "backend.tf already points to S3 — state migration was already completed."
  warn "If you need to re-migrate, manually restore backend.tf to 'backend \"local\" {}'"
  warn "and re-run this script."
  exit 0
fi

# ── Read outputs from existing local state ────────────────────────────────────
info "Reading outputs from local state..."

BUCKET=$(terraform output -raw tfstate_bucket_name 2>/dev/null) \
  || error "Could not read tfstate_bucket_name. Did you run 'terraform apply' first?"
REGION=$(terraform output -raw tfstate_bucket_region 2>/dev/null) \
  || error "Could not read tfstate_bucket_region."

info "  Bucket : $BUCKET"
info "  Region : $REGION"

STATE_KEY="bootstrap/terraform.tfstate"

# ── Verify bucket exists and is accessible ────────────────────────────────────
info "Verifying S3 bucket is accessible..."
aws s3api head-bucket --bucket "$BUCKET" --region "$REGION" \
  || error "Bucket '$BUCKET' not accessible. Check your AWS credentials and region."

# ── Rewrite backend.tf ────────────────────────────────────────────────────────
info "Rewriting $BACKEND_FILE with S3 backend..."

cat > "$BACKEND_FILE" <<EOF
# Generated by migrate.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
#
# Two-step pattern used during bootstrap:
#   Step 1 — backend "local" {} was active so 'terraform apply' could create
#            the S3 bucket before any remote state existed.
#   Step 2 — migrate.sh rewrote this file and ran 'terraform init -migrate-state'
#            to move the local state into the bucket below.
#
# Do not hand-edit this file. To add/change backends, update migrate.sh and rerun.
terraform {
  backend "s3" {
    bucket       = "${BUCKET}"
    key          = "${STATE_KEY}"
    region       = "${REGION}"
    encrypt      = true

    # Native S3 locking — no DynamoDB table needed (requires Terraform >= 1.10)
    use_lockfile = true
  }
}
EOF

info "$BACKEND_FILE updated."

# ── Migrate state ─────────────────────────────────────────────────────────────
info "Running 'terraform init -migrate-state'..."
terraform init -migrate-state -force-copy

info ""
info "──────────────────────────────────────────────────────"
info " Migration complete!"
info " State is now stored at:"
info "   s3://${BUCKET}/${STATE_KEY}"
info ""
info " Lock file (when a plan/apply is running):"
info "   s3://${BUCKET}/${STATE_KEY}.tflock"
info "──────────────────────────────────────────────────────"
