---
- name: ArgoCD Installation
  tasks:
    - name: Create argocd namespace
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: Apply ArgoCD manifests
      kubernetes.core.k8s:
        src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        state: present

    - name: Wait for ArgoCD pods to be ready
      kubernetes.core.k8s_info:
        namespace: argocd
        kind: Pod
      register: pods
      until: "pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == pods.resources | length"
      retries: 20
      delay: 30
