- name: Install Platform Services
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kubeconfig: "{{ ansible_env.KUBECONFIG }}"

  tasks:
    - name: Install ArgoCD
      include_role:
        name: argocd

    - name: Install Monitoring (Prometheus & Grafana)
      include_role:
        name: monitoring

    - name: Install Logging (Loki & Promtail)
      include_role:
        name: logging
